---
- name: my test playbook
  hosts: all
  become: true

  tasks:
  - name: install httpd package
    yum:
     name: httpd
     state: installed

  - name: service start
    service: 
      name: httpd
      state: started
