---
- name: create multi users
  hosts: all
  become: true
  tasks:
  - name: add list of users
    user: name='{{ item }}' state=present
    with_items:
      - mallik
      - mallik2
      - mallik3
